#!/usr/bin/env python3
"""
JPEG format switching verification script

Verify that the code modification is correct:
1. Whether deconstruct_pdf_to_images() uses JPEG format
2. Whether reconstruct_pdf() correctly handles JPEG files
3. Does the file extension match?
"""

import sys
import re
from pathlib import Path

#Add project path
sys.path.insert(0, str(Path(__file__).parent))

from compressor import pipeline


def test_deconstruct_function():
    """Test deconstruct_pdf_to_images function configuration"""
    print("=" * 70)
    print("Test 1: Check deconstruct_pdf_to_images() configuration")
    print("=" * 70)
    
    # Read function source code
    import inspect
    source = inspect.getsource(pipeline.deconstruct_pdf_to_images)
    
    # Check key parameters
    checks = {
        'Use JPEG format': '"-jpeg"' in source or '-jpeg' in source,
        'Set JPEG quality': 'jpegopt' in source or 'quality' in source,
        'Correct file extension': '*.jpg' in source or '.jpg' in source,
    }
    
    all_passed = True
    for check_name, result in checks.items():
        status = "✓ Passed" if result else "✗ Failed"
        print(f"  {check_name:30s}: {status}")
        if not result:
            all_passed = False
    
    #Extract quality parameters
    quality_match = re.search(r'quality[=\s]+(\d+)', source)
    if quality_match:
        quality = quality_match.group(1)
        print(f"\n Detected JPEG quality: {quality}")
        
        if 75 <= int(quality) <= 90:
            print(f" ✓ The quality parameters are reasonable (recommended range: 75-90)")
        else:
            print(f" ⚠️ Quality parameter {quality} may need to be adjusted")
    
    return all_passed


def test_reconstruct_function():
    """Test reconstruct_pdf function configuration"""
    print("\n" + "=" * 70)
    print("Test 2: Check reconstruct_pdf() configuration")
    print("=" * 70)
    
    import inspect
    source = inspect.getsource(pipeline.reconstruct_pdf)
    
    # Check if file extensions are processed dynamically
    checks = {
        'Dynamic acquisition of extension': 'suffix' in source or 'ext' in source,
        'Support JPEG files': '.jpg' in source,
        'Compatibility processing': 'if' in source and 'image_files' in source,
    }
    
    all_passed = True
    for check_name, result in checks.items():
        status = "✓ Passed" if result else "✗ Failed"
        print(f"  {check_name:30s}: {status}")
        if not result:
            all_passed = False
    
    return all_passed


def test_file_extension_consistency():
    """Test file extension consistency"""
    print("\n" + "=" * 70)
    print("Test 3: File extension consistency check")
    print("=" * 70)
    
    import inspect
    
    # Check deconstruct function
    deconstruct_source = inspect.getsource(pipeline.deconstruct_pdf_to_images)
    
    # Extract the generated file extension
    gen_ext = None
    if '*.jpg' in deconstruct_source:
        gen_ext = '.jpg'
    elif '*.tif' in deconstruct_source:
        gen_ext = '.tif'
    elif '*.png' in deconstruct_source:
        gen_ext = '.png'
    
    print(f"File type generated by deconstruct: {gen_ext}")
    
    # Check whether the reconstruct function can handle it correctly
    reconstruct_source = inspect.getsource(pipeline.reconstruct_pdf)
    
    if 'suffix' in reconstruct_source or 'ext' in reconstruct_source:
        print(f" ✓ reconstruct dynamically identifies file types (compatible with all formats)")
        return True
    elif gen_ext and gen_ext in reconstruct_source:
        print(f" ✓ reconstruct hardcoded match {gen_ext}")
        return True
    else:
        print(f" ✗ reconstruct may not handle {gen_ext} files correctly")
        return False


def test_import():
    """Test module import"""
    print("\n" + "=" * 70)
    print("Test 4: Module import check")
    print("=" * 70)
    
    try:
        from compressor import pipeline, strategy, utils
        print(" ✓ All modules imported successfully")
        
        # Check the existence of key functions
        functions = [
            'deconstruct_pdf_to_images',
            'analyze_images_to_hocr',
            'reconstruct_pdf',
        ]
        
        for func_name in functions:
            if hasattr(pipeline, func_name):
                print(f" ✓ Function exists: {func_name}")
            else:
                print(f" ✗ Missing function: {func_name}")
                return False
        
        return True
        
    except Exception as e:
        print(f" ✗ Import failed: {e}")
        return False


def print_summary(results):
    """Print test summary"""
    print("\n" + "=" * 70)
    print("Summary of test results")
    print("=" * 70)
    
    for test_name, result in results.items():
        status = "✓ Passed" if result else "✗ Failed"
        print(f"  {test_name:40s}: {status}")
    
    all_passed = all(results.values())
    
    print("\n" + "=" * 70)
    if all_passed:
        print("🎉 All tests passed! JPEG format switching completed.")
        print("=" * 70)
        print("\nNext step:")
        print("1. Run the test script to verify different quality parameters:")
        print("   python test_jpeg_compression.py testpdf.pdf")
        print()
        print("2. Test the complete process using real PDF:")
        print("   python main.py --input test.pdf --output ./out -k")
        print()
        print("3. Check the file size in the temporary directory:")
        print("   ls -lh /tmp/tmpXXXXXX/page-*.jpg")
        print()
        print("4. Comparing the final PDF quality of JPEG and previous TIFF")
        print()
        print("5. If you need to adjust quality parameters, modify pipeline.py:")
        print(' "-jpegopt", "quality=85" # Adjust to 70-95')
        return 0
    else:
        print("❌ Some tests failed, please check the code.")
        print("=" * 70)
        return 1


def main():
    print("\n" + "🔥" * 35)
    print("JPEG format switching verification")
    print("🔥" * 35 + "\n")
    
    results = {}
    
    #Run all tests
    results['module import'] = test_import()
    results['deconstruct function configuration'] = test_deconstruct_function()
    results['reconstruct function configuration'] = test_reconstruct_function()
    results['File extension consistency'] = test_file_extension_consistency()
    
    return print_summary(results)


if __name__ == '__main__':
    sys.exit(main())
