# compressor/splitter.py

import logging
import math
from pathlib import Path
from . import utils, pipeline

def run_splitting_strategy(compression_results, output_dir, args):
    """
    Implement new split strategy.
    This strategy does not perform secondary compression, but only physically splits the selected best master.

    Args:
        compression_results (dict): All intermediate results generated by the compression phase.
        output_dir (Path): final output directory.
        args (argparse.Namespace): command line parameters.

    Returns:
        bool: Whether the split was successful.
    """
    logging.info("=== Start new version of splitting strategy ===")
    
    # Pre-check: Make sure there is a compression result smaller than 8MB
    all_results = compression_results.get('all_results', {})
    if not all_results:
        logging.error("❌ Split failed: No compression results are available for splitting.")
        return False
    
    under_8mb = [res for res in all_results.values() if res.get('size_mb', float('inf')) <= 8.0]
    if not under_8mb:
        logging.error("❌ Splitting failed: All compression results are larger than 8MB, and valid splitting cannot be performed.")
        return False
    
    logging.info(f"✓ Found {len(under_8mb)} compressed results smaller than 8MB and can be split.")
    
    # 1. Select Splitting Source
    source_to_split = _select_splitting_source(compression_results)
    if not source_to_split:
        logging.error("Split failed: No suitable split master found in the compression results.")
        return False

    source_path = source_to_split['path']
    source_size_mb = source_to_split['size_mb']
    logging.info(f"Selected split master: {source_path.name}, size: {source_size_mb:.2f}MB")

    # 2. Calculate Page Density
    total_pages = pipeline.get_pdf_page_count(source_path)
    if total_pages == 0:
        logging.error(f"Unable to obtain the page number of {source_path.name}, split aborted.")
        return False
    
    page_density = source_size_mb / total_pages
    logging.info(f"Master total pages: {total_pages}, average page density: {page_density:.4f} MB/page")

    # 3. Determine Optimal Split Count
    target_size_mb = args.target_size
    try:
        split_count = _determine_optimal_split_count(source_size_mb, target_size_mb, args.max_splits)
    except ValueError as e:
        logging.error(f"Split failed: {e}")
        return False
    
    logging.info(f"Target number of splits: {split_count} parts")

    # 4. Calculate Pages per Split
    try:
        split_plan = _calculate_split_plan(total_pages, split_count, page_density, target_size_mb)
    except ValueError as e:
        logging.error(f"Split failed: Unable to plan page allocation.{e}")
        return False

    logging.info("Generate split plan:")
    for i, part in enumerate(split_plan, 1):
        logging.info(f" - Part {i}: Page {part['start']} - {part['end']} ({part['pages']} page)")

    # 5. Execute Physical Split
    logging.info("Starting to perform physical split...")
    original_stem = Path(args.input).stem
    
    for i, part_info in enumerate(split_plan, 1):
        part_path = output_dir / f"{original_stem}_part{i}.pdf"
        success = _split_pdf_physical(
            source_path,
            part_path,
            part_info['start'],
            part_info['end']
        )
        if not success:
            logging.error(f"Failed to split part {i}.")
            # Theoretically qpdf is very stable. If it fails, it is usually an IO problem and it will fail directly.
            return False
    
    logging.info("All parts have been split successfully!")
    # Clean up the temporary directories left behind during the compression phase
    temp_dir_of_compression = source_path.parent
    if getattr(args, 'keep_temp_on_failure', False) is False:
        utils.cleanup_directory(temp_dir_of_compression)
    return True

def _select_splitting_source(all_results):
    """
    Select the best split master from all compression results.
    Rules:
    1. Find files whose size is closest to 8MB but <= 8MB.
    2. If not, select the smallest of all results.
    """
    if not all_results:
        return None

    # Filter out results that are less than or equal to 8MB
    under_8mb = [res for res in all_results.values() if res['size_mb'] <= 8.0]

    if under_8mb:
        # Among results smaller than 8MB, sort in descending order of size and take the first one (closest to 8MB)
        best_source = sorted(under_8mb, key=lambda x: x['size_mb'], reverse=True)[0]
        logging.info(f"Find {len(under_8mb)} candidate masters less than 8MB, select the largest one.")
        return best_source
    else:
        # If there is no result smaller than 8MB, select the smallest one among all results.
        logging.warning("No compression results smaller than 8MB were found, the smallest one will be selected as the split master.")
        smallest_source = sorted(all_results.values(), key=lambda x: x['size_mb'])[0]
        return smallest_source

def _determine_optimal_split_count(source_size_mb, target_size_mb, max_splits):
    """
    Calculate the optimal number of splits k.
    """
    if source_size_mb <= target_size_mb:
        # This situation should not happen in theory, because if the requirements are met, the compression will succeed
        logging.warning("The split master size has met the requirements, but the split is still started. Will split into 2 parts by default.")
        return 2

    min_k = math.ceil(source_size_mb / target_size_mb)
    
    if min_k > max_splits:
        raise ValueError(f"Even splitting by target size {target_size_mb}MB requires {min_k} parts, exceeding the maximum limit {max_splits}.")

    return int(min_k) if min_k > 1 else 2

def _calculate_split_plan(total_pages, k, page_density, target_size_mb):
    """
    Dynamically calculate the page range for each section.
    """
    plan = []
    
    # Calculate the maximum number of pages that a single section can accommodate (safety red line)
    # Leave a little buffer, for example 98%
    safe_target_size = target_size_mb * 0.98
    if page_density == 0:
        # Avoid divide-by-zero errors, although unlikely
        raise ValueError("The page density is 0 and split planning cannot be performed.")
    max_pages_per_part = math.floor(safe_target_size / page_density)
    if max_pages_per_part == 0:
        raise ValueError(f"Page density is too high ({page_density:.4f} MB/page), single page size has exceeded the target.")

    logging.debug(f"Safe maximum number of pages per split part: {max_pages_per_part}")

    start_page = 1
    remaining_pages = total_pages
    
    for i in range(k):
        remaining_parts = k - i
        
        # Calculate the number of pages that should be allocated for the current section
        if remaining_parts == 1:
            # The last part, allocate all remaining pages
            pages_for_this_part = remaining_pages
        else:
            # Dynamically calculate the average number of pages
            avg_pages = math.ceil(remaining_pages / remaining_parts)
            # Cannot exceed the safety red line
            pages_for_this_part = min(avg_pages, max_pages_per_part)

        end_page = start_page + pages_for_this_part - 1
        
        # Make sure the total number of pages is not exceeded
        if end_page > total_pages:
            end_page = total_pages
            pages_for_this_part = end_page - start_page + 1

        plan.append({
            'start': start_page,
            'end': end_page,
            'pages': pages_for_this_part
        })

        start_page = end_page + 1
        remaining_pages -= pages_for_this_part

        if remaining_pages <= 0 and i < k - 1:
            # The number of pages has been allocated in advance, indicating that the plan is wrong or the number of pages is too few.
            logging.warning(f"The number of pages has been allocated in part {i+1}, and the actual split will be less than the planned part {k}.")
            break
    
    # Final verification
    if sum(p['pages'] for p in plan) != total_pages or (plan and plan[-1]['end'] != total_pages):
        # This is a health check and should not happen in theory
        raise RuntimeError(f"Page allocation plan generation error: total number of pages does not match. Total number of planned pages: {sum(p['pages'] for p in plan)}, actual total number of pages: {total_pages}")

    return plan

def _split_pdf_physical(pdf_path, output_path, start_page, end_page):
    """
    Use qpdf for purely physical splitting.
    """
    logging.info(f"Splitting {pdf_path.name}: page number {start_page}-{end_page} -> {output_path.name}")
    command = [
        "qpdf",
        str(pdf_path),
        "--pages",
        ".", # represents the input file
        f"{start_page}-{end_page}",
        "--",
        str(output_path)
    ]
    return utils.run_command(command)